//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { LocationEntity } from './db/Location.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [SettingsEntity, LocationEntity];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Location: [
        {
          name: 'name 1',
          description: 'description 1',
          coordinates: 'coordinates 1',
          type: 'type 1',
          proximity: 'proximity 1',
          id: 60,
        },
        {
          name: 'name 2',
          description: 'description 2',
          coordinates: 'coordinates 2',
          type: 'type 2',
          proximity: 'proximity 2',
          id: 88,
        },
        {
          name: 'name 3',
          description: 'description 3',
          coordinates: 'coordinates 3',
          type: 'type 3',
          proximity: 'proximity 3',
          id: 1,
        },
        {
          name: 'name 4',
          description: 'description 4',
          coordinates: 'coordinates 4',
          type: 'type 4',
          proximity: 'proximity 4',
          id: 69,
        },
        {
          name: 'name 5',
          description: 'description 5',
          coordinates: 'coordinates 5',
          type: 'type 5',
          proximity: 'proximity 5',
          id: 11,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('LocationEntity', data.Location);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
