//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Location: [
      {
        name: 'name 1',
        description: 'description 1',
        coordinates: 'coordinates 1',
        type: 'type 1',
        proximity: 'proximity 1',
        id: 60,
      },
      {
        name: 'name 2',
        description: 'description 2',
        coordinates: 'coordinates 2',
        type: 'type 2',
        proximity: 'proximity 2',
        id: 88,
      },
      {
        name: 'name 3',
        description: 'description 3',
        coordinates: 'coordinates 3',
        type: 'type 3',
        proximity: 'proximity 3',
        id: 1,
      },
      {
        name: 'name 4',
        description: 'description 4',
        coordinates: 'coordinates 4',
        type: 'type 4',
        proximity: 'proximity 4',
        id: 69,
      },
      {
        name: 'name 5',
        description: 'description 5',
        coordinates: 'coordinates 5',
        type: 'type 5',
        proximity: 'proximity 5',
        id: 11,
      },
    ],
  },
};
export default data;
