//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Location: {
      name: 'Location',
      fields: {
        name: 'Name',
        description: 'Description',
        coordinates: 'Coordinates',
        type: 'Type',
        proximity: 'Proximity',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Location: {
      name: 'Location (fr)',
      fields: {
        name: 'Name (fr)',
        description: 'Description (fr)',
        coordinates: 'Coordinates (fr)',
        type: 'Type (fr)',
        proximity: 'Proximity (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
